/******************************************************************************
 * Inverse Kinematics for 4/6 legged bots using 3DOF lizard legs
 *
 * Auto-Generated by NUKE!
 *   http://arbotix.googlecode.com
 *
 * FRONT VIEW       ^        ==0         0==
 *     /\___/\      |       |  0==[___]==0  |
 *    /       \     Z       |               |
 *
 * TOP VIEW
 *    \       /     ^
 *     \_____/      |
 *  ___|     |___   X
 *     |_____|
 *     /     \      Y->
 *    /       \
 *****************************************************************************/

#ifndef NUKE
#define NUKE

#define LEG_COUNT   6
#define SERVO_COUNT 18

/* Body
 * We assume 4 legs are on the corners of a box defined by X_COXA x Y_COXA
 * Middle legs for a hexapod can be different Y, but should be halfway in X
 */
#define X_COXA      60  // MM between front and back legs /2
#define Y_COXA      60  // MM between front/back legs /2
#define M_COXA      100  // MM between two middle legs /2

/* Legs */
#define L_COXA      52  // MM distance from coxa servo to femur servo
#define L_FEMUR     82 // MM distance from femur servo to tibia servo
#define L_TIBIA     140 // MM distance from tibia servo to foot

/* Servo IDs */
#define RM_TIBIA 18
#define RF_COXA 2
#define LR_TIBIA 11
#define LF_FEMUR 3
#define RF_TIBIA 6
#define RM_FEMUR 16
#define RM_COXA 14
#define RR_COXA 8
#define LF_TIBIA 5
#define LF_COXA 1
#define LR_FEMUR 9
#define RR_FEMUR 10
#define LM_TIBIA 17
#define RF_FEMUR 4
#define LM_FEMUR 15
#define RR_TIBIA 12
#define LM_COXA 13
#define LR_COXA 7

#define RIGHT_FRONT    0
#define RIGHT_REAR     1
#define LEFT_FRONT     2
#define LEFT_REAR      3
#define RIGHT_MIDDLE   4
#define LEFT_MIDDLE    5

typedef struct {
    double x, y, z;
} vector3;

extern int mins[SERVO_COUNT+1];
extern int maxs[SERVO_COUNT+1];

enum {COXA_SERVO, FEMUR_SERVO, TIBIA_SERVO, DEGREES_OF_FREEDOM};
extern int servoIds[LEG_COUNT][DEGREES_OF_FREEDOM];
extern int servoToLeg[SERVO_COUNT+1];
extern int servoToJoint[SERVO_COUNT+1];
extern int coxaX[LEG_COUNT];
extern int coxaY[LEG_COUNT];

#endif

